src/Fooidity.Management.Web/Models/ApplicationViewModel.cs
namespace Fooidity.Management.Web.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    using System.Web.Mvc;


    public class ApplicationViewModel
    {
        [Display(Name = "Application Id")]
        public string Id { get; set; }

        public string Name { get; set; }

        public string OrganizationId { get; set; }

        [Display(Name = "Organization")]
        public string OrganizationName { get; set; }

        public List<string> Keys { get; set; }

        public List<OrganizationViewModel> Organizations { get; set; }

        public IEnumerable<SelectListItem> OrganizationItems
        {
            get { return Organizations.Select(x => new SelectListItem {Value = x.Id, Text = x.Name}); }
        }

        public IEnumerable<CodeFeatureStateViewModel> Features { get; set; }
    }
}

src/Fooidity.Management.Web/Controllers/ApplicationController.cs
namespace Fooidity.Management.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using Commands;
    using Fooidity.Contracts;
    using Management.Models;
    using Microsoft.AspNet.Identity;
    using Models;
    using Queries;


    [Authorize]
    public class ApplicationController :
        Controller
    {
        readonly ICommandHandler<ICreateApplication, IUserOrganizationApplication> _createApplication;
        readonly ICommandHandler<ICreateApplicationKey, IOrganizationApplicationKey> _createApplicationKey;
        readonly ICommandHandler<IUpdateApplicationCodeFeatureState> _updateApplicationCodeFeatureState;
        readonly IQueryHandler<IGetApplication, IUserOrganizationApplication> _getApplication;
        readonly IQueryHandler<IListApplications, IEnumerable<IUserOrganizationApplication>> _getApplications;
        readonly IQueryHandler<IListApplicationCodeFeatures, IEnumerable<ICodeFeatureState>> _listApplicationCodeFeatures;
        readonly IQueryHandler<IListApplicationKeys, IEnumerable<IOrganizationApplicationKey>> _listApplicationKeys;
        readonly IQueryHandler<IListOrganizations, IEnumerable<IOrganization>> _listOrganizations;

        public ApplicationController(IQueryHandler<IListApplications, IEnumerable<IUserOrganizationApplication>> getApplications,
            IQueryHandler<IListOrganizations, IEnumerable<IOrganization>> listOrganizations,
            ICommandHandler<ICreateApplication, IUserOrganizationApplication> createApplication,
            IQueryHandler<IGetApplication, IUserOrganizationApplication> getApplication,
            IQueryHandler<IListApplicationKeys, IEnumerable<IOrganizationApplicationKey>> listApplicationKeys,
            ICommandHandler<ICreateApplicationKey, IOrganizationApplicationKey> createApplicationKey,
            IQueryHandler<IListApplicationCodeFeatures, IEnumerable<ICodeFeatureState>> listApplicationCodeFeatures, ICommandHandler<IUpdateApplicationCodeFeatureState> updateApplicationCodeFeatureState)
        {
            _getApplications = getApplications;
            _listOrganizations = listOrganizations;
            _createApplication = createApplication;
            _getApplication = getApplication;
            _listApplicationKeys = listApplicationKeys;
            _createApplicationKey = createApplicationKey;
            _listApplicationCodeFeatures = listApplicationCodeFeatures;
            _updateApplicationCodeFeatureState = updateApplicationCodeFeatureState;
        }

        public async Task<ActionResult> Index(CancellationToken cancellationToken = default(CancellationToken))
        {
            IEnumerable<IUserOrganizationApplication> results =
                await _getApplications.Execute(new ListApplications(User.Identity.GetUserId()), cancellationToken);

            return View(results.Select(x => new ApplicationViewModel
            {
                Id = x.ApplicationId,
                Name = x.ApplicationName,
                OrganizationId = x.OrganizationId,
                OrganizationName = x.OrganizationName,
            }));
        }

        public async Task<ActionResult> Details(string id, CancellationToken cancellationToken)
        {
            var userId = User.Identity.GetUserId();

            IUserOrganizationApplication application = 
                await _getApplication.Execute(new GetApplication(userId, id), cancellationToken);

            IEnumerable<IOrganizationApplicationKey> applicationKeys =
                await _listApplicationKeys.Execute(new ListApplicationKeys(userId, id), cancellationToken);

            IEnumerable<ICodeFeatureState> codeFeatures =
                await _listApplicationCodeFeatures.Execute(new ListApplicationCodeFeatures(userId, id),
                    cancellationToken);

            return View(new ApplicationViewModel
            {
                Id = application.ApplicationId,
                Name = application.ApplicationName,
                OrganizationId = application.OrganizationId,
                OrganizationName = application.OrganizationName,
                Keys = applicationKeys.Select(x => x.Key).ToList(),
                Features = codeFeatures.Select(x => new CodeFeatureStateViewModel
                {
                    CodeFeatureId = new CodeFeatureId(x.CodeFeatureId),
                    Enabled = x.Enabled,
                    LastUpdated = x.LastUpdated,
                }).ToList(),
            });
        }

        public async Task<ActionResult> Create(CancellationToken cancellationToken)
        {
            IEnumerable<IOrganization> results =
                await _listOrganizations.Execute(new ListOrganizations(User.Identity.GetUserId()), cancellationToken);

            return View(new ApplicationViewModel
            {
                Organizations = results.Select(x => new OrganizationViewModel {Id = x.OrganizationId, Name = x.OrganizationName}).ToList(),
            });
        }

        [HttpPost]
        public async Task<ActionResult> Create(ApplicationViewModel model, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                ICreateApplication command = new CreateApplication(User.Identity.GetUserId(), model.OrganizationId, model.Name, DateTime.UtcNow, Guid.NewGuid());

                IUserOrganizationApplication application = await _createApplication.Execute(command, cancellationToken);

                return RedirectToAction("Details", new {id = application.ApplicationId});
            }

            return View();
        }

        public async Task<ActionResult> CreateKey(CreateApplicationKeyViewModel model, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                var command = new CreateApplicationKey(User.Identity.GetUserId(), model.OrganizationId, model.ApplicationId, DateTime.UtcNow,
                    Guid.NewGuid());

                IOrganizationApplicationKey key = await _createApplicationKey.Execute(command, cancellationToken);

                return RedirectToAction("Details", new {id = model.ApplicationId});
            }

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Enable(EnableCodeFeatureViewModel model, CancellationToken cancellationToken)
        {
            return await UpdateCodeFeatureState(model, cancellationToken, true);
        }

        public async Task<ActionResult> Disable(EnableCodeFeatureViewModel model, CancellationToken cancellationToken)
        {
            return await UpdateCodeFeatureState(model, cancellationToken, false);
        }

        async Task<ActionResult> UpdateCodeFeatureState(EnableCodeFeatureViewModel model, CancellationToken cancellationToken, bool enabled)
        {
            if (ModelState.IsValid)
            {
                var codeFeatureId = new Uri(model.CodeFeatureId);
                var timestamp = DateTime.UtcNow;

                var command = new UpdateApplicationCodeFeatureState(model.ApplicationId, codeFeatureId, enabled, timestamp);

                await _updateApplicationCodeFeatureState.Execute(command, cancellationToken);

                return RedirectToAction("Details", new {id = model.ApplicationId});
            }

            return RedirectToAction("Index");
        }
    }
}

src/Fooidity.Management.Web/Controllers/CodeFeatureController.cs
namespace Fooidity.Management.Web.Controllers
{
    using System.Linq;
    using System.Threading;
    using System.Threading.Tasks;
    using System.Web.Mvc;
    using Management.Models;
    using Microsoft.AspNet.Identity;
    using Models;
    using Queries;


    [Authorize]
    public class CodeFeatureController :
        Controller
    {
        readonly IQueryHandler<IGetCodeFeatureDetail, ICodeFeatureDetail> _getCodeFeatureDetail;

        public CodeFeatureController(IQueryHandler<IGetCodeFeatureDetail, ICodeFeatureDetail> getCodeFeatureDetail)
        {
            _getCodeFeatureDetail = getCodeFeatureDetail;
        }

        public async Task<ActionResult> Details(ManageCodeFeatureViewModel model, CancellationToken cancellationToken)
        {
            if (ModelState.IsValid)
            {
                var getCodeFeatureDetail = new GetCodeFeatureDetail(User.Identity.GetUserId(), model.ApplicationId, model.CodeFeatureId);

                ICodeFeatureDetail detail = await _getCodeFeatureDetail.Execute(getCodeFeatureDetail, cancellationToken);

                return View(new CodeFeatureDetailViewModel
                {
                    ApplicationId = detail.ApplicationId,
                    ApplicationName = detail.ApplicationName,
                    CodeFeatureId = detail.CodeFeatureId,
                    CurrentState = new CodeFeatureStateViewModel
                    {
                        CodeFeatureId = new CodeFeatureId(detail.CurrentState.CodeFeatureId),
                        Enabled = detail.CurrentState.Enabled,
                        LastUpdated = detail.CurrentState.LastUpdated
                    },
                    StateHistory = detail.StateHistory.Select(x => new CodeFeatureStateViewModel
                    {
                        CodeFeatureId = new CodeFeatureId(x.CodeFeatureId),
                        Enabled = x.Enabled,
                        LastUpdated = x.LastUpdated
                    }).ToArray(),
                });
            }

            return RedirectToAction("Index", "Application");
        }
    }
}

src/Fooidity.Management.Web/Views/Application/Create.cshtml
@model Fooidity.Management.Web.Models.ApplicationViewModel

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>ApplicationViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.OrganizationId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(model => model.OrganizationId, Model.OrganizationItems, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.OrganizationId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

src/Fooidity.Management.Web/Views/Application/Details.cshtml
@using Fooidity.Management.Models
@model Fooidity.Management.Web.Models.ApplicationViewModel

@{
    ViewBag.Title = "Application Details";
}

<h2>Application Details</h2>

<div>
    <h4>Application</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>

        <dd>
            <code>@Html.DisplayFor(model => model.Id)</code>
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OrganizationName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OrganizationName)
        </dd>
    </dl>

    <h4>Application Keys</h4>
    <hr />
    <p>
        @Html.ActionLink("Create New", "CreateKey", new { organizationId = Model.OrganizationId, applicationId = Model.Id })
    </p>
    <table class="table">
        <tr>
            <th>
                Key
            </th>
            <th></th>
        </tr>

        @foreach (string key in Model.Keys)
        {
            <tr>
                <td>
                    <code>@key</code>
                </td>
                <td>
                    @*                        @Html.ActionLink("Details", "Details", new { id = item.Id })*@
                </td>
            </tr>
        }

    </table>
    
    <h4>Code Features</h4>
    <hr/>
    <table class="table">
        <tr>
            <th>
                Code Feature Id
            </th>
            <th>
                Enabled
            </th>
            <th>
                Last Updated (UTC)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model.Features.OrderBy(x => x.CodeFeatureId.Name))
        {
            <tr>
                <td>
                    @Html.ActionLink(item.CodeFeatureId.Name, "Details", "CodeFeature", new { applicationId = Model.Id, codeFeatureId = item.CodeFeatureId }, new { })
                    <dl class="dl-horizontal">
                        <dt>
                            Namespace
                        </dt>

                        <dd>
                            @Html.DisplayFor(modelItem => item.CodeFeatureId.Namespace)
                        </dd>

                        <dt>
                            Assembly
                        </dt>

                        <dd>
                            @Html.DisplayFor(modelItem => item.CodeFeatureId.Assembly)
                        </dd>
                    </dl>
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Enabled)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastUpdated)
                </td>
                <td>
                    @Html.ActionLink("Enable", "Enable", new { applicationId = Model.Id, codeFeatureId = item.CodeFeatureId }) |
                    @Html.ActionLink("Disable", "Disable", new { applicationId = Model.Id, codeFeatureId = item.CodeFeatureId })
                </td>
            </tr>
        }

    </table>

</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

src/Fooidity.Management.Web/Views/Application/Index.cshtml
@using Fooidity.Management.Web.Models
@model IEnumerable<ApplicationViewModel>

@{
    ViewBag.Title = "Applications";
}

<h2>Applications</h2>
<p>
    An application defines a scope of managed features. Applications connect to the portal using the Fooidity Client, which 
    automatically adds features to the application as they are evaluated. Once added, users can toggle features on and off.
    If a switch uses a context, the context is also reported, allowing the configuration of context-specific feature states.
</p>

<p>
    @Html.ActionLink("Create New", "Create", new { @class="btn btn-primary" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.OrganizationName)
        </th>
        <th></th>
    </tr>

    @foreach (ApplicationViewModel item in Model.OrderBy(x => x.OrganizationName).ThenBy(x => x.Name))
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.OrganizationName)
            </td>
            <td>
                @Html.ActionLink("Details", "Details", new {id = item.Id})
            </td>
        </tr>
    }

</table>